const globalMsg = {
  EMAIL_ALREADY_EXISTS: "Email already exists.",
  SUCCESS: "SUCCESS",
  BOOKING_CREATE_SUCCESS: "Booking creation success.",
  UPLOAD_SUCC: "Upload success.",
  USER_CREATE_ERROR: "USER_CREATE_ERROR",
  SOMETHING_WENT_WRONG: "Somthing went Wrong",
	INVALID_CREDENTIALS: "Invalid Credantials",
	SIGNUP_SUCCESS_MESSAGE: "Sign In Success",
	SIGNUP_ERROR_MESSAGE: "Error Sign in",
	LOGIN_SUCCESS_MESSAGE: "Login Successfully",
	LOGIN_ERROR_MESSAGE: "Error logging in",
	USER_ALREADT_EXIST: "User Already Exist",
	INVALID_EMAIL: "Invalid Email",
	INVALID_PASSWORD: "Invalid Password",
	ACCESS_DENIED: "Access Denied",
	USER_NOT_FOUND: "User not found",
	MOVIE_ADDED_MESSAGE: "Movie added",
	MOVIE_UPDATED_MESSAGE: "Movie updated",
	MOVIE_DELETED_MESSAGE: "Movie deleted",
	PROVIDE_MOVIE_ID: "PROVIDE_MOVIE_ID",
	MOVIE_NOT_FOUND: "Movie not found",
	NO_DATA_FOUND: "No data found",
	ERROR_FETCHING: "Error fetching",
	INVALID_PAGE_OR_PAGE_SIZE: "INVALID_PAGE_OR_PAGE_SIZE",
  UNAUTHORIZED: "Unauthorized.",
  CREATED_SUCCESSFULLY: "Created successfully.",
  REGISTERED_SUCCESSFULLY: "Registerd Successfully.",
  FETCH_DATA_SUCCESSFULLY: "Fetch data Successfully.",
  UPDATED_SUCCESSFULLY: "Updated successfully.",
  DELTED_SUCESSFULLY: "Deleted successfully.",
  DEACTIVATE_SUCESSFULLY: "Deactivated successfully.",
};

export default globalMsg;
